'use strict';

/**
 * S3 utility – presigned PUT URLs for venue images.
 * Bucket: venuemanagementdhruva
 * Folder structure: uploads/images/{entityId}/{uuid}-{filename}
 */

const { S3Client, PutObjectCommand, DeleteObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');
const { randomUUID } = require('crypto');

const BUCKET = process.env.S3_BUCKET || 'venuemanagementdhruva';
const REGION = process.env.AWS_REGION || process.env.REGION || 'ap-south-1';

const UPLOADS_PREFIX = 'uploads';

/** Supported upload folders. */
const UPLOAD_FOLDER_TYPES = Object.freeze(['images']);

const s3Client = new S3Client({ region: REGION });

/**
 * Strip path traversal, limit length, allow only safe characters.
 * @param {string} fileName
 * @param {number} maxLength
 * @returns {string}
 */
function sanitizeFileName(fileName, maxLength = 200) {
  if (!fileName || typeof fileName !== 'string') return 'file';
  const base = fileName.replace(/^.*[/\\]/, '').trim();
  const safe = base.replace(/[^\w.\-]/g, '_').slice(0, maxLength);
  return safe || 'file';
}

/**
 * Build S3 key: uploads/{folderType}/{entityId}/{uuid}-{sanitizedFileName}
 * @param {'images'} folderType
 * @param {string} entityId - e.g. venueId, spaceId. Defaults to 'misc'.
 * @param {string} fileName
 * @returns {string}
 */
function buildUploadKey(folderType, entityId, fileName) {
  const safeType = UPLOAD_FOLDER_TYPES.includes(folderType) ? folderType : 'images';
  const safeId = (entityId || 'misc').toString().trim().replace(/\s+/g, '') || 'misc';
  const safeName = sanitizeFileName(fileName);
  return `${UPLOADS_PREFIX}/${safeType}/${safeId}/${randomUUID()}-${safeName}`;
}

/**
 * Get a presigned PUT URL for a single file upload.
 * @param {string} key - S3 object key
 * @param {string} contentType - MIME type
 * @param {number} [expiresIn=900] - Seconds until URL expires (default 15 min)
 * @returns {Promise<string>}
 */
async function getPresignedPutUrl(key, contentType, expiresIn = 900) {
  const command = new PutObjectCommand({
    Bucket: BUCKET,
    Key: key,
    ContentType: contentType || 'application/octet-stream',
  });
  return getSignedUrl(s3Client, command, { expiresIn });
}

/**
 * Returns the public HTTPS URL of an object.
 * @param {string} key
 * @returns {string}
 */
function getPublicUrl(key) {
  return `https://${BUCKET}.s3.${REGION}.amazonaws.com/${key}`;
}

/**
 * Delete an object by key.
 * @param {string} key
 */
async function deleteObject(key) {
  await s3Client.send(new DeleteObjectCommand({ Bucket: BUCKET, Key: key }));
}

/**
 * Extract S3 key from a public URL generated by getPublicUrl().
 * @param {string} fileUrl
 * @returns {string|null}
 */
function keyFromUrl(fileUrl) {
  if (!fileUrl || typeof fileUrl !== 'string') return null;
  const escapedBucket = BUCKET.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(`https://${escapedBucket}\\.s3\\.[^/]+\\.amazonaws\\.com/(.+)`);
  const match = fileUrl.trim().match(pattern);
  return match ? match[1] : null;
}

/**
 * Ensure the key lives under our uploads prefix (prevents deleting arbitrary bucket keys).
 * @param {string} key
 */
function assertUploadKey(key) {
  if (!key || typeof key !== 'string' || !key.trim()) throw new Error('Invalid key');
  if (!key.startsWith(`${UPLOADS_PREFIX}/`)) {
    throw new Error(`Key must start with ${UPLOADS_PREFIX}/`);
  }
}

module.exports = {
  getPresignedPutUrl,
  getPublicUrl,
  buildUploadKey,
  deleteObject,
  keyFromUrl,
  assertUploadKey,
  sanitizeFileName,
  BUCKET,
  REGION,
  UPLOADS_PREFIX,
  UPLOAD_FOLDER_TYPES,
};
